#!/usr/bin/env python3
import json

with open('/Users/yepz/JSweb/data/modules.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

text_m129 = '''Lógica Algorítmica: el arte preciso de enseñar a pensar a las máquinas

Imagina por un momento lúdico e instructivo que debes enseñarle pacientemente a un visitante explorador alienígena de un planeta remoto y gélido, que jamás ha visto agua líquida hirviendo en su vida, el proceso cotidiano exacto, seguro y meticuloso para prepararse una humeante taza matutina de té caliente oscuro. No bastaría de ninguna manera con entregarle amablemente los ingredientes aromáticos y los recipientes de cerámica; tendrías que detallar asiduamente, paso a paso, de manera absolutamente cristalina, estructurada e inquebrantable, cómo calentar el vital líquido en la estufa, a qué temperatura exacta apagar el fuego inestable, cómo sumergir la delicada hoja botánica y cuánto tiempo temporal exacto esperar antes de lograr el consumo seguro óptimo. Esta minuciosa, ordenada y estricta disección analítica secuencial de un problema complejo y difuso en pequeñas piezas de solución manejable, predecible y lógica es la esencia profunda de todo el software contemporáneo, una coreografía intelectual que llamamos diseño computacional algorítmico lógico.

En el centro absoluto de este noble y elegante arte intelectual de resolución de problemas reside el indispensable **algoritmo** (algorithm: secuencia finita de pasos para resolver un problema). Lejos de ser un hechizo mágico oscuro de matemáticos o un misterio indescifrable, un algoritmo es simplemente una receta de cocina matemática moderna extremadamente rigurosa, clara, lógica y estructurada. Es un conjunto finito, ordenado y predecible de instrucciones precisas e inequívocas que transforman un estado inicial de confusión o incertidumbre de datos crudos en una solución clara, elegante y final. Desde el complejo mecanismo subyacente de búsqueda algorítmica de internet que prioriza la página web más relevante del mundo hasta los cálculos balísticos atmosféricos precisos que guían el aterrizaje suave de un pesado módulo espacial lunar robótico, todos son algoritmos matemáticos meticulosamente diseñados que siguen un sendero lógico predeterminado irrompible sin lugar a la improvisación emocional humana.

Antes de que los arquitectos de código escriban laboriosamente la primera instrucción real en un lenguaje de programación formal sintácticamente restrictivo como Python o C++, suelen visualizar el flujo invisible de los datos mediante un útil **diagrama de flujo** (flowchart: representación visual sistemática de un proceso). Estos esquemas gráficos organizados conectan ingeniosamente formas geométricas como rombos de decisión, rectángulos de proceso y óvalos de inicio y fin con flechas direccionales que representan visualmente el viaje de la información a través del tiempo. Esta perspectiva geométrica visual de la lógica abstracta permite a los ingenieros astutos detectar cuellos de botella teóricos ocultos, fallas estructurales analíticas peligrosas y bucles eternos de repetición lógica mucho antes de escribir una sola línea de complejo código fuente y enviarlo a compilar. Es el plano arquitectónico indispensable de cualquier programa bien cimentado.

Otra herramienta fundamental y universal para bocetar lógicas computacionales complejas sin las ataduras técnicas del compilador es el versátil **pseudocódigo** (pseudocode: lenguaje informal estructurado para planificar algoritmos). Es una narración escrita intermedia, un híbrido lingüístico flexible y poderoso que combina las palabras comunes del lenguaje humano cotidiano con la rigurosa jerarquía lógica matemática de la programación pura formal. Al eliminar la preocupación ansiosa y tediosa por colocar correctamente las comas faltantes, los paréntesis estrictos y la rígida sintaxis del frío silicio compilado, los creadores ágiles de software pueden concentrarse exclusivamente y profundamente en la pura resolución conceptual de problemas abstractos, construyendo un andamio intelectual lógico sólido que luego será traducido fielmente al crudo lenguaje definitivo de las máquinas digitales de silicio.

Dos engranajes analíticos vitales impulsan la complejidad abrumadora de cualquier algoritmo moderno exitoso del mundo. Primero, tenemos el valioso **condicional** (conditional statement: regla de decisión basada en verdadero o falso) que otorga valientemente a la dócil máquina el invaluable poder de la elección binaria bifurcada simulando una forma básica de pensamiento. Evalúa matemáticamente una condición específica del entorno, dictando que si una variable ocurre de cierto modo natural esperado, se siga el camino de código principal, pero si resulta matemáticamente falsa, se ejecute una instrucción de emergencia alternativa. Este simple acto de decisión es lo que permite que el software sea interactivo e inteligente.

Segundo, y no menos importante, tenemos la indispensable e imparable **iteración** (iteration: repetición cíclica de una secuencia de instrucciones), que permite a la computadora robótica repetir incansable, paciente y velozmente una misma tarea matemática aburrida y rutinaria millones de veces consecutivas. Mientras un oficinista humano caería irremediablemente presa de la fatiga extrema, el aburrimiento y el error por distracción al sumar mil recibos de papel a mano, el procesador aplica iteraciones lógicas superando colosalmente la frágil paciencia y la fatiga mental humana, hasta alcanzar asombrosamente una meta estipulada matemática final perfecta en microsegundos y sin un solo error humano biológico natural. Es esta combinación de decisiones condicionales dinámicas y repeticiones iterativas incansables lo que da vida a toda la magia del software global en nuestra época.

Caso de estudio: el sistema de navegación interplanetaria del rover Perseverance.
En la gélida, polvorienta y roja superficie oxidada del remoto planeta Marte, los delicados comandos electrónicos enviados desde las potentes antenas de la lejana Tierra tardan preciosos e intolerables minutos astronómicos de luz en llegar al vehículo explorador, haciendo imposible que un controlador humano terrestre conduzca directamente el valioso avance mecánico con un mando remoto tradicional en tiempo real. Perseverance confía su destino rodante y valioso a robustos algoritmos de evasión autónoma espacial fotográfica. Al iterar millones de cálculos analíticos estereoscópicos de densas rocas marcianas y aplicando veloces y sabios saltos condicionales precisos de seguridad, decide, sin ninguna intervención terrestre humana, si debe sortear audazmente un cráter arenoso peligroso o detenerse pacíficamente en su lugar para salvaguardar su integridad mecánica estructural ante un inminente riesgo físico insalvable en el inhóspito polvo desértico rojizo de otro mundo antiguo planetario.

Conexiones Profesionales y Campo Laboral.
El diseño analítico lógico, el dibujo geométrico de flujos complejos organizacionales y la creación eficiente de fuertes esquemas iterativos condicionales son habilidades indispensables y transversales en exigentes campos globales como la bioinformática genómica moderna, la compleja ingeniería aeroespacial matemática, la ciencia computacional de bases de datos profundas empresariales y el crucial desarrollo financiero bancario en línea. Las grandes mentes lógicas del presente estructuran elegantemente soluciones escalables críticas de software robusto, arquitecturas logísticas de transporte internacional marítimo, avanzadas redes de inteligencia artificial automatizada de gran escala y robustos sistemas analíticos comerciales a escala internacional, donde la precisión algorítmica perfecta es indispensable para el éxito económico.

Preguntas de Reflexión y Análisis.
1. Muchos problemas cotidianos humanos pacíficos habituales diarios, como decidir qué ruta urbana tomar de improviso al salir rápidamente desesperadamente del oscuro hogar al amanecer, son procesados y resueltos de forma algorítmica e instintiva por nuestro propio cerebro biológico asombroso de supervivencia. ¿Qué paso mental condicional lógico de decisión binaria o acción repetitiva fundamental iterativa usas tú personalmente de forma diaria, cotidiana y repetitiva sin darte cuenta conscientemente para resolver este persistente desafío personal de navegación peatonal o de conducción urbana metropolitana?
2. Si un algoritmo lógico fundamental utilizado exhaustivamente y de forma implacable en una crítica máquina médica hospitalaria de reanimación tiene un importante salto condicional de emergencia ligeramente mal programado desde su origen estructural humano analítico de software comercial, ¿cuáles podrían ser las dolorosas, trágicas y letales consecuencias severas reales físicas innegables en el frágil entorno biológico de la aplicación directa de ese dispositivo clínico interactivo en pacientes confiados, asustados y humanos hospitalizados?
3. El flexible texto de pseudocódigo no obedece rígidamente a ningunas de las complicadas reglas estrictas de sintaxis tipográfica de ningún estricto motor compilador técnico real del silicio del procesador informático físico moderno. ¿Por qué, entonces, los profesores universitarios veteranos exigentes, sabios y experimentados en sistemas lógicos valoran abrumadoramente más la gran habilidad de un joven estudiante para escribir y estructurar lógicamente este esquema narrativo abstracto en lugar de simplemente forzarlo a escribir de inmediato largos comandos oscuros binarios crudos directos compilables de un frío lenguaje sintáctico técnico real y funcional de silicio?

Resumen rápido de conceptos clave.
**algoritmo** (algorithm: secuencia finita de pasos para resolver un problema).
**diagrama de flujo** (flowchart: representación visual sistemática de un proceso).
**pseudocódigo** (pseudocode: lenguaje informal estructurado para planificar algoritmos).
**condicional** (conditional statement: regla de decisión basada en verdadero o falso).
**iteración** (iteration: repetición cíclica de una secuencia de instrucciones).'''

ch = data['chapters'][5]
mod = ch['modules'][2]
mod['fullText'] = text_m129

with open('/Users/yepz/JSweb/data/modules.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

words = len(text_m129.split())
print(f"Module 5.3 words: {words}")
