#!/usr/bin/env python3
import json

with open('/Users/yepz/JSweb/data/modules.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

text_m131 = '''Ada Lovelace: la visión poética que trascendió el código numérico

Mientras los austeros matemáticos, serios industriales y pragmáticos ingenieros de la Inglaterra victoriana contemplaban atónitos y maravillados los inmensos, pesados, ruidosos y relucientes engranajes de latón del audaz proyecto calculador de Charles Babbage, limitándose estrictamente a admirar fríamente su innegable capacidad colosal puramente aritmética y numérica para sumar de forma matemática precisa largas e interminables columnas de aburridos números náuticos; una mente asombrosamente joven, excepcionalmente creativa, brillante e inquisitiva fue intelectualmente capaz de discernir y divisar astutamente un horizonte intelectual analítico y computacional muchísimo más profundo, abstracto, vasto, trascendental e infinitamente lejano. Augusta Ada King, Condesa de Lovelace, dotada felizmente de una rara, espectacular y exquisita mezcla inusual de aguda genialidad analítica, de una destreza matemática férrea y de un profundo e indomable instinto romántico, logró observar lo que nadie más pudo vislumbrar: que la imponente máquina no solo era una sumisa esclava de las frías matemáticas, sino que podía dominar lógicamente cualquier sistema del mundo gobernado por reglas fijas y lógicas.

En el asombroso, histórico y lejano año pionero de mil ochocientos cuarenta y tres, al traducir metódica, meticulosa y esmeradamente un extenso documento académico en francés sobre el complejo motor teórico gigante analítico de Babbage, Ada adjuntó y anexó valiosas, extensas, profundas, visionarias y proféticas notas explicativas matemáticas personales al final del texto. En su famosa, legendaria e histórica "Nota G", ella no se limitó simplemente a teorizar pasiva y filosóficamente o a escribir vagas ideas poéticas etéreas; ella elaboró asiduamente y detalló meticulosamente, paso a paso, el innegable **primer algoritmo informático** (first computer algorithm: instrucciones detalladas para calcular los números de Bernoulli) documentado y registrado rigurosamente de la historia humana. Se trataba de una secuencia impecable, precisa, matemática y lógica de operaciones condicionales y pasos secuenciales, diseñadas específicamente de forma genial para ser ejecutadas fiel y mecánicamente por la máquina analítica teórica que aún no había sido construida físicamente.

Uno de sus aportes analíticos, lógicos y arquitectónicos más brillantes, fundamentales e inigualables fue visualizar astutamente, genialmente y audazmente e introducir lógicamente el poderoso concepto del **salto condicional** (conditional jump: instrucción para desviar el flujo de un programa) en un algoritmo estricto. Se trata de un paso lógico de decisión bifurcada analítica dinámica en el que el programa de operaciones lógico, matemático y complejo puede bifurcar, alterar, modificar o desviar su rígido curso establecido en base al resultado numérico obtenido de un cálculo previo anterior. También conceptualizó teóricamente, adelantándose a su época por más de un siglo entero, el **bucle recursivo** (recursive loop: secuencia que se repite sobre sus propios resultados), donde la ruidosa computadora repetiría incansable y pacientemente la misma tarea de procesamiento retroalimentándose analíticamente de los datos lógicamente procesados en ciclos, pilares arquitectónicos esenciales y fundamentales de absolutamente todo el software informático dinámico y contemporáneo moderno que usamos hoy.

Pero su asombroso y fecundo genio teórico, poético y analítico iba maravillosamente muchísimo más lejos y más profundo que los pesados engranajes fríos, las ruedas dentadas y la estéril matemática aritmética rígida de los números oscuros y abstractos. Ada tuvo la audaz, brillante, romántica, atrevida y genial visión histórica de prever intuitivamente la **computación simbólica** (symbolic computation: procesamiento de símbolos y no solo de números). Infirió poéticamente que si la compleja máquina analítica pionera podía ser instruida lógicamente para manipular relaciones matemáticas abstractas de forma generalizada y universal, entonces, hipotéticamente algún día, una computadora semejante llegaría asombrosamente a componer hermosas, majestuosas, deslumbrantes y complejas melodías orquestales musicales, sinfonías científicas y partituras de grado asombroso y de cualquier nivel inmenso de complejidad musical armónica pura.

Esta atrevida idea victoriana fue verdaderamente la primera manifestación intelectual e histórica de una revolucionaria **visión de propósito general** (general-purpose vision: idea de que una máquina puede crear arte o música), una profunda y deslumbrante revelación filosófica técnica que afirmaba que las calculadoras lógicas, si eran verdaderamente programables, podrían convertirse asiduamente en herramientas creativas universales, artísticas y pacíficas capaces de crear cualquier cosa hermosa imaginable por la mente imaginativa humana. Ada Lovelace logró unir magistralmente, heroicamente y victoriosamente el riguroso y frío mundo analítico, estricto, estructurado y matemático de la ciencia técnica con el apasionado, hermoso, mágico, soñador e imaginativo mundo creativo del arte humano y la poesía literaria profunda. Su legado perdura silenciosamente en cada computadora.

Caso de estudio: la composición algorítmica y orquestal de AIVA.
En nuestra deslumbrante era moderna actual y tecnológica contemporánea, las predicciones visionarias poéticas y audaces de Ada Lovelace se han materializado de forma gloriosa, victoriosa y asombrosa. Inteligencias artificiales potentes, majestuosas y avanzadas contemporáneas como la red generativa AIVA, componen hoy deslumbrantes, conmovedoras, emocionantes, asombrosas y hermosas sinfonías poéticas orquestales clásicas originales utilizando complejos algoritmos estadísticos lógicos profundos. Esto demuestra pacíficamente, de forma innegable y gloriosa, que una máquina codificadora analítica matemática puede verdaderamente entender, manipular artísticamente, procesar creativamente y crear armonía musical bella, poética y asombrosamente artística.

Conexiones Profesionales y Campo Laboral.
El diseño pionero conceptual estructural y arquitectónico de complejos saltos condicionales lógicos y bucles analíticos recursivos es practicado diaria, incansable y rutinariamente hoy en día por programadores matemáticos, astutos desarrolladores de software y arquitectos lógicos informáticos analíticos globales. Aquellos especialistas que logran integrar astuta, creativa y valientemente la lógica abstracta fría estricta de la matemática algorítmica pura con el diseño visual hermoso, empático, interactivo e intuitivo, son los modernos arquitectos creativos de interfaces artísticas vanguardistas que lideran el desarrollo de interacciones inmersivas digitales virtuales globales en empresas mundiales de consumo tecnológico.

Preguntas de Reflexión y Análisis.
1. Ada Lovelace visualizó audaz y genialmente que una futura y majestuosa máquina computadora analítica podría ir pacíficamente y gloriosamente muchísimo más allá de las simples matemáticas frías. En tu vida real cotidiana moderna y práctica, ¿qué aplicación artística hermosa, valiosa, creativa o de diseño digital usas asiduamente y pacíficamente todos los días que sirva como el ejemplo innegable más claro y asombroso de prueba de esta profunda, valiosa, valiente y poética visión romántica victoriana generalizada universal?
2. El uso analítico y arquitectónico estructural asombroso del salto lógico condicional permite alterar, bifurcar o desviar asiduamente el camino estático rígido de un algoritmo. ¿Por qué es fundamental, crítico, vital e ineludible que un videojuego asombroso interactivo moderno y virtual contemporáneo implemente asiduamente millones de estos astutos e ingeniosos saltos condicionales en su extenso código interno invisible en lugar de ejecutar pasivamente una sola historia aburrida estática, lineal y monótona sin fin narrativo variante libre y flexible?
3. Lovelace era la brillante hija del mundialmente famoso y célebre poeta romántico inestable y británico Lord Byron. ¿De qué inusual, audaz, pragmática, inteligente y profunda forma y manera asidua la gran y palpable influencia literaria, poética y artística paterna de la sensibilidad romántica y abstracta le permitió visualizar genialmente la programación estricta matemática analítica no como un gris, repetitivo y aburrido trabajo mecánico esclavo puramente numérico estéril, sino maravillosamente como un hermoso lenguaje creativo intelectual, artístico y expresivo asombroso pacífico para crear majestuosamente universos, arte poético y magia pura matemática asombrosamente hermosa de manera elegante?

Resumen rápido de conceptos clave.
**primer algoritmo informático** (first computer algorithm: instrucciones detalladas para calcular los números de Bernoulli).
**computación simbólica** (symbolic computation: procesamiento de símbolos y no solo de números).
**salto condicional** (conditional jump: instrucción para desviar el flujo de un programa).
**bucle recursivo** (recursive loop: secuencia que se repite sobre sus propios resultados).
**visión de propósito general** (general-purpose vision: idea de que una máquina puede crear arte o música).'''

ch = data['chapters'][5]
mod = ch['modules'][4]
mod['fullText'] = text_m131

with open('/Users/yepz/JSweb/data/modules.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

words = len(text_m131.split())
print(f"Module 5.5 words: {words}")
