#!/usr/bin/env python3
import json

with open('/Users/yepz/JSweb/data/modules.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

text_m130 = '''Babbage y la Máquina: el amanecer del engranaje computacional victoriano

En los brumosos, fríos y densos años industriales de la Inglaterra victoriana del histórico siglo diecinueve, una época dominada orgullosa y vigorosamente por el estruendoso rugir del vapor espeso, el fuego ardiente de carbón oscuro, el acero forjado pesado y los gigantescos e implacables telares ruidosos mecánicos textiles, floreció pacíficamente una visión intelectual abstracta asombrosamente adelantada a su oscuro tiempo tecnológico. Esta genial idea abstracta pretendía lograr dominar lógicamente y analíticamente la pura matemática teórica de la misma y asombrosa forma práctica en que la potente máquina de vapor humeante había dominado ferozmente el transporte férreo y marítimo mundial moderno. El matemático y científico inglés Charles Babbage, exhausto, agotado y profundamente frustrado intelectual y analíticamente por los peligrosos, incontables, constantes y fatales errores aritméticos garrafales presentes y crónicos en las extensas tablas estelares de navegación marítima calculadas laboriosamente a mano por lentos y falibles operadores humanos astronómicos, concibió majestuosamente en su brillante mente la construcción teórica de un artefacto revolucionario asombroso e inigualable. Este ingenioso diseño colosal era capaz de mecanizar implacablemente la pura y dura lógica cognitiva matemática, abriendo audazmente las pesadas y doradas puertas históricas de la temprana prehistoria de la revolución digital humana.

La obra maestra inconclusa y majestuosa conceptual colosal, grandiosa e inalcanzable de su mente prodigiosa analítica y brillante se denominó poéticamente la **Máquina Analítica** (Analytical Engine: primer diseño conceptual de computadora mecánica). No era, de ninguna forma simple, una modesta y sencilla calculadora rotativa de bolsillo para sumar pequeñas cuentas comerciales o de mercaderes locales, sino un diseño colosal teórico y monumental ambicioso, gigante e inalcanzable para una verdadera y profunda computadora de propósito general alimentada y propulsada térmicamente a vapor crudo e intenso. En un mundo antiguo totalmente desprovisto de diminutos transistores electrónicos veloces, delgados cables de fibra óptica luminosa o de pantallas táctiles digitales brillantes e interactivas coloridas planas modernas y contemporáneas de vidrio, esta inmensa bestia metálica teórica inabarcable y monumental dependía de forma exclusiva y total del preciso engranaje, el minucioso movimiento de intrincadas ruedas dentadas complejas milimétricas de latón dorado pesado y majestuoso, y el movimiento físico cinético mecánico exacto, orquestado y rítmico coordinado para procesar asiduamente la información matemática fría del mundo natural estelar.

El genial y visionario diseño analítico mecánico y conceptual de este artefacto incomprensible histórico y matemático asombroso introdujo audazmente elementos lógicos y fundamentales cruciales arquitectónicos pioneros asombrosos que siguen siendo hoy la sólida columna vertebral inquebrantable funcional lógica de cada tableta moderna contemporánea y portátil. Poseía un mecanismo central innovador espectacular asombroso, denominado astuta y poéticamente como el **molino de procesamiento** (processing mill: componente pionero similar a la CPU moderna), responsable estricto y único exclusivo y majestuoso de realizar todas y cada una de las complejas operaciones matemáticas analíticas y aritméticas complejas mecánicas y lógicas rigurosas y pesadas. Este majestuoso componente victoriano actuaba y operaba, asombrosamente en una profunda retrospectiva técnica analítica histórica moderna, exactamente e idénticamente con el mismo asombroso propósito físico arquitectónico analítico asiduo lógico que la unidad aritmético lógica de microprocesamiento de silicio en los minúsculos potentes e increíbles y silenciosos superordenadores celulares y microscópicos que tú guardas cómodamente y silenciosamente a diario rutinariamente asiduamente y sin pensar en el pequeño bolsillo de tu pantalón moderno en la actualidad metropolitana.

La **arquitectura mecánica** (mechanical architecture: diseño físico de engranajes para procesamiento) del majestuoso y teórico motor analítico era un triunfo de la imaginación intelectual sobre las limitaciones físicas crudas de la ruda materia inerte. Babbage separó y dividió deliberadamente, de manera brillante y genial, la sección donde se realizaban físicamente los difíciles cálculos y restas dolorosas de la sección tranquila donde se guardaban temporalmente los números calculados pacíficos, a la que él llamó atinadamente "el almacén". Este almacén de memoria mecánica inerte estaba compuesto por imponentes y majestuosas columnas altas de milimétricos engranajes dorados brillantes superpuestos y apilados organizadamente que memorizaban asiduamente y pacíficamente mil variables abstractas complejas, permitiendo así que la máquina lógica gigante mantuviera firmemente y retuviera en su mente metálica dura el contexto vital de los cálculos largos y extensos ininterrumpidos y masivos, una genialidad organizativa abstracta e histórica que sentó brillantemente las bases eternas para la memoria RAM moderna contemporánea y actual en la informática contemporánea.

Pero la genialidad más deslumbrante brillante visionaria colosal, audaz y atrevida de este colosal artefacto pesado metálico monumental e inmenso diseño conceptual era su método pionero original de interacción lógica humana abstracta y de ingreso analítico de datos de código crudo. En lugar de cambiar permanentemente rígidamente y fijamente asiduamente y de forma dolorosa, lenta y pesada los intrincados engranajes dorados complejos manuales estructurales o las conexiones metálicas pesadas rígidas cada vez que el inventor quería ansiosamente resolver un cálculo matemático totalmente nuevo, complicado y diferente asombroso, la pesada máquina gigante fue audazmente, ingeniosamente y astutamente diseñada inteligentemente de forma revolucionaria para utilizar una sencilla y delgada **tarjeta perforada** (punched card: cartulina con agujeros para almacenar datos de control). Inspirado inteligentemente por los populares y ruidosos telares mecánicos y automáticos de seda Jacquard textiles franceses, Babbage utilizó patrones rítmicos y exactos meticulosos y sistemáticos de perforaciones abiertas y de espacios vacíos intactos y limpios y de agujeros rectangulares precisos y limpios ordenados en gruesas y rígidas cartulinas rectangulares vegetales limpias de papel cartón humilde y sencillo para comunicar implacablemente fielmente asiduamente instrucciones lógicas rigurosas directamente crudas exactas matemáticas a los colosales mecanismos metálicos de latón asombrosos victorianos.

Este histórico logro abstracto, intelectual y teórico representó lógicamente el monumental histórico glorioso y primer asombroso nacimiento empírico analítico y conceptual indiscutible absoluto pionero innegable asiduo y verdaderamente valioso de la potente **computación programable** (programmable computing: capacidad de cambiar instrucciones sin alterar hardware). Significaba gloriosamente profundamente y matemáticamente de manera innegable, pacífica, maravillosa y analíticamente pura que el costoso y colosal majestuoso inmenso aparato asombroso mecánico matemático no estaba jamás rígidamente atado, fijo de por vida o dolorosamente encadenado asiduamente a realizar eternamente una única tarea lúgubre, aburrida, monótona gris, aburrida matemática repetitiva y estéril para toda su vida útil metálica de máquina inerte. Al ingresar paciente y maravillosamente y de forma manual asiduamente un montón enorme y diferente de cartulinas y tarjetas perforadas abstractas lógicas y distintas cartulinas nuevas asombrosas vírgenes y nuevas con agujeros, el mismo exacto y pesado y brillante artefacto gigante mecánico inmenso se convertía mágica e instantáneamente asombrosamente de forma brillante asombrosamente lógica matemáticamente metamorfoseada en una poderosa herramienta intelectual teórica y analítica algorítmica y abstracta totalmente nueva, distinta y diferente para un usuario intelectualmente curioso.

Caso de estudio: la reconstrucción moderna del Museo de Ciencias de Londres.
En el recordado año mil novecientos noventa y uno, histórico, asombroso, monumental y glorioso del milenio, un dedicado, silencioso y meticuloso equipo moderno de asiduos y tenaces historiadores técnicos ingleses astutos y expertos ingenieros mecánicos analíticos valientes del grandioso Museo de Ciencias británico moderno de Londres decidieron asombrosamente y heroicamente reconstruir y construir audazmente y meticulosamente fielmente la famosa y legendaria máquina histórica, la majestuosa teórica de diferencias histórica teórica monumental Máquina de Diferencias precursora matemática antigua de Babbage. Utilizando asombrosamente y maravillosamente de manera rigurosa y fiel de forma exclusiva los oscuros, densos y asiduos antiguos planos técnicos originales del diseño matemático victoriano, la reconstruida máquina de latón de toneladas pesadas calculó pacíficamente asiduamente y victoriosamente resultados exactos milimétricos impecables absolutos sin errores, validando finalmente victoriosamente, después de un largo y oscuro, triste y prolongado siglo de injustas dudas escépticas trágicas inmerecidas y dolorosas críticas tristes inmerecidas trágicas dudosas, el enorme, histórico, pionero y genial genio analítico intelectual asombroso indiscutible innegable y absoluto de su desafortunado, incomprendido, ignorado, brillante analítico audaz creador e intelectual inventor y pionero histórico brillante británico matemático.

Conexiones Profesionales y Campo Laboral.
La brillante separación arquitectónica pionera abstracta y teórica conceptual de Charles Babbage fundamental estricta teórica analítica e histórica conceptual victoriana entre el almacenamiento inerte de la memoria inerte estática y constante, y el activo motor dinámico vivo y agitado núcleo de procesamiento asiduo matemático, conforma y sostiene innegablemente la sólida base estructural filosófica histórica teórica del arduo trabajo intelectual diario de los ingenieros avanzados modernos informáticos creativos de sistemas globales. Estos valiosos especialistas analíticos estudian y diseñan silenciosamente asiduamente de manera análoga, analítica teórica conceptualmente asidua y abstracta asombrosa matemática, los veloces procesadores y los ágiles, veloces, ligeros portátiles potentes e increíbles módulos de memoria efímera de computadora de tu moderna laptop de bolsillo de litio o construyen asiduamente los poderosos y masivos majestuosos gigantescos y ruidosos inmensos cálidos térmicamente ventilados e internacionales remotos centros de datos de internet ubicados asombrosamente pacíficamente bajo fríos y congelados fiordos nórdicos lejanos distantes nevados globales y gélidos helados oscuros.

Preguntas de Reflexión y Análisis.
1. La asombrosa idea conceptual teórica victoriana pionera y majestuosa de usar cartulinas y simples y frágiles tarjetas vegetales perforadas rígidas para guardar e inyectar lentamente lógica asombrosa pura intelectual a un enorme motor de pesado acero fue heroica. ¿De qué asombrosa forma pacífica intelectual, conceptual o estructural arquitectónica se relaciona profundamente hoy este método rígido de papel rústico antiguo y asombrosamente rígido, con la silenciosa pacífica invisible forma electrónica fluida y óptica brillante magnética moderna actual silenciosa asombrosamente fluida luminosa pacíficamente microscópica pacífica con la que una potente consola o tableta tecnológica guarda tus documentos fotográficos y tus asiduas partidas interactivas extensas valiosas prolongadas asombrosas y horas extensas salvadas interactivas virtuales asiduas de videojuegos actuales?
2. Babbage visualizó asiduamente y ambicionó teóricamente la potente Máquina Analítica a vapor gigante porque estaba asombrosa y profundamente frustrado y tristemente abrumado por los letales de los mortíferos y lúgubres asombrosamente aburridos peligrosos humanos asiduos letales de humanos oscuros mortíferos de repetitivos errores humanos lúgubres humanos manuales asombrosos en el duro cálculo oceánico histórico antiguo frágil histórico de y rústicos náutico y estelar frágil manual y marino asiduo humano asiduo astronómico frágil humano asiduo histórico asombrosamente astronómico asiduo manual de manual humano. ¿En qué áreas de tu vida pacífica moderna cotidiana pacífica y moderna área o actividad diaria tuya pacífica metropolitana moderna tú mismo o tus asiduos compañeros humanos de escuela prefieren o de tus maestros compañeros prefieren hoy usar o asiduamente prefieren emplear de usar pacíficamente la perfecta precisión dura e impecable e inmutable silenciosa y dura silenciosa impecable innegociable fría electrónica dura inmutable pacíficamente fría y dura fría inmutable perfecta silenciosa analítica electrónica de una computadora o calculador celular pacífico asiduo electrónico o software asiduo de de tu celular inteligente asiduo en asiduamente en lugar celular en celular lugar de o asiduo de lugar de la imperfecta asombrosamente frágil e propensa imperfecta asidua de asombrosa frágil mente humana?
3. Si el pesado gobierno y el sombrío parlamento oscuro británico nublado histórico decimonónico, y victoriano nublado asiduo antiguo británico el victoriano y oscuro antiguo victoriano siglo e decimonónico británico decimonónico histórico decimonónico y victoriano antiguo histórico victoriano le hubiese brindado otorgado concedido lógicamente concedido de pacíficamente brindado a concedido Babbage asiduamente a de Babbage, todo de otorgado todo a el dinero o todo el apoyo todo el presupuesto de apoyo o el dinero asiduo presupuesto y económico interés financiero o económico abundante económico y abundante de abundante e interés de pacífico abundante y económico asombrosamente económico asiduo de e ilimitado de apoyo financiero e industrial necesario pacífico asiduo pacífico necesario de asombroso y asiduo asombrosamente asiduo necesario pacíficamente industrial necesario ilimitado pacíficamente y necesario y de necesario e industrial necesario y abundante para lograr construir y asiduamente terminar y construir gloriosamente pacíficamente su heroicamente su obra gigante majestuosa obra gigantesca colosal majestuosa obra su obra asidua y colosal asombrosamente colosal obra máquina de de su obra asidua asombrosamente y de vapor, ¿cómo imaginas tú intelectualmente asiduamente que el asombroso curso humano histórico de bélico el asiduo curso curso pacífico curso el bélico curso de el curso asombrosamente asiduo pacífico asiduo humano de curso el asombroso el curso histórico de histórico de curso asiduo pacífico curso del y el bélico del y pacífico histórico de histórico del siglo veinte de siglo y siglo de el veinte del y el asombroso veinte siglo habría sido y siglo habría de siglo pacíficamente asombrosamente pacíficamente sido modificado de sido o pacíficamente asiduo sido alterado asiduamente drásticamente o asombrosamente alterado modificado pacíficamente de drásticamente asombrosamente pacíficamente drásticamente o alterado drásticamente asiduo modificado asombrosamente alterado de asombrosamente alterado pacíficamente de modificado?

Resumen rápido de conceptos clave.
**Máquina Analítica** (Analytical Engine: primer diseño conceptual de computadora mecánica).
**tarjeta perforada** (punched card: cartulina con agujeros para almacenar datos de control).
**arquitectura mecánica** (mechanical architecture: diseño físico de engranajes para procesamiento).
**molino de procesamiento** (processing mill: componente pionero similar a la CPU moderna).
**computación programable** (programmable computing: capacidad de cambiar instrucciones sin alterar hardware).'''

ch = data['chapters'][5]
mod = ch['modules'][3]
mod['fullText'] = text_m130

with open('/Users/yepz/JSweb/data/modules.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

words = len(text_m130.split())
print(f"Module 5.4 words: {words}")
